### DISCUSSION TITLE
Agents in rootless container

### DISCUSSION THREAD

**Discussion by BAStos525** [pyToshka/docker-wazuh-agent#141] [General]
Hi! I'm trying to deploy wazuh-agents on kubernetes nodes as rootless container. In Dockerfile, we can add a new user with id 1001 and give him `chown` and `chmod` permissions under `/var/ossec/` path. The same things could be done for already existing user `wazuh` after `wazuh-agent` package installation with id 999.
So, in DaemonSet we can try the following securityContext:
```
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
```
But every time it goes to the error:
```
{"timestamp": 1718371198.769759, "message": "Error during importing key: 2024/06/14 13:19:58 manage_agents: CRITICAL: (1130): Unable to switch to group 'wazuh' due to [(1)-(Operation not permitted)]. "}
{"timestamp": 1718371198.779344, "message": "error during restarting Wazuh agent: 2024/06/14 13:19:58 wazuh-execd: CRITICAL: (1130): Unable to switch to group 'wazuh' due to [(1)-(Operation not permitted)].\n"}
...
{"timestamp": 1718371206.081851, "message": "Waiting for Wazuh agent <...> become ready current status is never_connected......"}
```
Log entity ` switch to group 'wazuh` appears any time doesn't matter which user is selected in Dockerfile and id DaemonSet securityContext if it is not root user.
It is bind to `/var/ossec/bin/manage_agents` binary. Any ideas how it could be possible to resolve or even it's able to run wazuh-agent in rootless container overall?
