### ISSUE TITLE
Issue with registering agent 

### ISSUE THREAD

**Issue by samba1112** [pyToshka/docker-wazuh-agent#13]
When using agent getting below error
![image](https://user-images.githubusercontent.com/76871147/198584541-509a68ae-e6d4-41fd-bb3a-5767b42f0596.png)

**Comment by pyToshka** [comment]
@samba1112  could you please show your configs as well as what the wazuh version?

**Comment by samba1112** [comment]
Using this image @pyToshka 
![image](https://user-images.githubusercontent.com/76871147/198593281-3c2f133b-d493-4100-85a9-61cce3864d95.png)

**Comment by samba1112** [comment]
@pyToshka and may be i should give specific version below 4.2.7 or equal version instead of 4.x like this?
![image](https://user-images.githubusercontent.com/76871147/198595531-c46df020-4459-464c-bea4-2be504f43b76.png)

**Comment by pyToshka** [comment]
@samba1112  I meant show please variables. I didnt test for 4.2.7, last deployment was for version 4.3.9.

**Comment by samba1112** [comment]
```apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
      name: wazuh-agent
    spec:
      hostPID: true
      hostIPC: true
      containers:
      - name: wazuh-agent
        image: kennyopennix/wazuh-agent:latest
        livenessProbe:
          httpGet:
            path: /healz
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        ports:
          - name: agent-http
            containerPort: 5000
            protocol: TCP
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: JOIN_MANAGER_MASTER_HOST
          value: "wazuh-master.local"
        - name: JOIN_MANAGER_WORKER_HOST
          value: "wazuh-manager.local"
        - name: JOIN_MANAGER_PROTOCOL
          value: "https"
        - name: FLASK_BIND
          value: "0.0.0.0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JOIN_MANAGER_USER
          valueFrom:
            secretKeyRef:
              name: wazuh-api-cred
              key: username
        - name: JOIN_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-api-cred
              key: password      
        - name: WAZUH_GROUPS
          value: default
        - name: JOIN_MANAGER_API_PORT
          value: "55000"
        - name: JOIN_MANAGER_PORT
          value: "1514"
        - name: HEALTH_CHECK_PROCESSES
          value: "ossec-execd,ossec-syscheckd,ossec-logcollector,wazuh-modulesd,ossec-authd"
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /host/dev
          name: dev
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/etc
          name: etc
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/boot
          name: boot
          readOnly: true
        - mountPath: /host/usr
          name: usr
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules
          readOnly: true
        - mountPath: /host/var/log
          name: log
          readOnly: true
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: var-run
        hostPath:
          path: /var/run
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: boot
        hostPath:
          path: /boot
      - name: usr
        hostPath:
          path: /usr
      - name: modules
        hostPath:
          path: /lib/modules
      - name: log
        hostPath:
          path: /var/log
```

**Comment by samba1112** [comment]
@pyToshka This is mountpath for wazuh manager

![image](https://user-images.githubusercontent.com/76871147/198606223-752828c8-3355-4ee8-b235-56cc0f3174f1.png)

**Comment by samba1112** [comment]
yes we are using ingress so given that ingress endpoint there @pyToshka

**Comment by pyToshka** [comment]
@samba1112  i didnt test via  ingress, i use "service"
As well below my example, this example working for me.
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      name: wazuh-agent
      creationTimestamp: null
      labels:
        app: wazuh-agent
    spec:
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
            type: ''
        - name: log
          hostPath:
            path: /var/log
            type: ''
      containers:
        - name: wazuh-agent
          image: ""
          ports:
            - name: agent-http
              containerPort: 5000
              protocol: TCP
          env:
            - name: JOIN_MANAGER_MASTER_HOST
              value: wazuh.wazuh.svc.cluster.local
            - name: JOIN_MANAGER_WORKER_HOST
              value: wazuh-workers.wazuh.svc.cluster.local
            - name: JOIN_MANAGER_PROTOCOL
              value: https
            - name: FLASK_BIND
              value: 0.0.0.0
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WAZUH_GROUPS
              value: default
            - name: JOIN_MANAGER_USER
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: JOIN_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: JOIN_MANAGER_API_PORT
              value: '55000'
            - name: JOIN_MANAGER_PORT
              value: '1514'
            - name: HEALTH_CHECK_PROCESSES
              value: >-
                ossec-execd,ossec-syscheckd,ossec-logcollector,wazuh-modulesd,ossec-authd
          resources: {}
          volumeMounts:
            - name: docker-socket-mount
              mountPath: /var/run/docker.sock
            - name: docker-socket-mount
              mountPath: /host/var/run/docker.sock
            - name: log
              readOnly: true
              mountPath: /host/var/log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      hostPID: true
      hostIPC: true
      securityContext: {}
      schedulerName: default-scheduler
  
```
