### ISSUE TITLE
Running wazuh-agent as root user

### ISSUE THREAD

**Issue by Sabreen-Parveen** [pyToshka/docker-wazuh-agent#22]
The agent runs as root user by default, I want to run it as another user, but I get permission denied, is there a way I can use a non-root user?

**Comment by Sabreen-Parveen** [comment]
When I am using the latest image of the wazuh-agent, I am getting this error:
```
{"timestamp": 1683700897.137182, "message": "Error during importing key: 2023/05/10 06:41:37 manage_agents: CRITICAL: (1130): Unable to switch to group 'wazuh' due to [(1)-(Operation not permitted)]. "}
{"timestamp": 1683700897.148454, "message": "error during restarting Wazuh agent: 2023/05/10 06:41:37 wazuh-execd: CRITICAL: (1130): Unable to switch to group 'wazuh' due to [(1)-(Operation not permitted)].\n"}
```
I tried adding wazuh user to wazuh group but that also doesn't help.

My docker-compose file:
  ```
version: "3.2"

  services:
    wazuh-agent:
      container_name:
        wazuh-agent
      image: kennyopennix/wazuh-agent:sha-cadbcc0
      hostname: ${HOST}
      volumes:
        - /etc/os-release:/etc/os-release
        - /var/run/docker.sock:/var/run/docker.sock
        - /:/rootfs:ro
        - ./ossec.jinja2:/var/ossec/ossec.jinja2
        - ./local_internal_options.jinja2:/var/ossec/etc/local_internal_options.jinja2
      network_mode: "host"
      pid: "host"
      environment:
        - JOIN_MANAGER_MASTER_HOST=${MASTER_HOST_IP}
        - JOIN_MANAGER_WORKER_HOST=${WORKER_HOST_IP}
        - JOIN_MANAGER_PASSWORD=${API_PASSWORD}
        - JOIN_MANAGER_USER=${API_USERNAME}
        - WAZUH_GROUPS=${env}
      restart: always
      logging:
        options:
          tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
```
